#!/usr/bin/env python3
"""Deep strict BTC 5M backtest on complete second-level markets.

Goals:
1. Use only complete/usable markets from the current collector.
2. Study the last 60 seconds of each market at second resolution.
3. Sweep the primary strategy parameters requested by the user:
   - entry window: T-60s .. T-1s
   - minimum probability: 95% .. 99%
   - minimum absolute gap: 20 .. 200
4. Compare staking modes and pause-after-profit rules on the exact trade
   sequence generated by the strict strategy.

This script does not use the archived simulated trade stream. It derives
signals directly from:
- derived/market_integrity.jsonl
- true_market/price_ticks.jsonl
- true_market/orderbook_ticks.jsonl
"""

from __future__ import annotations

import json
import math
import statistics
from bisect import bisect_right
from collections import Counter, defaultdict
from dataclasses import dataclass
from datetime import datetime, timedelta, timezone
from pathlib import Path
from typing import Any, Dict, Iterable, List, Optional, Tuple

CN = timezone(timedelta(hours=8))
FEE_RATE = 0.07
AMOUNT_USD = 1.0
MAX_ORDERBOOK_AGE_SECONDS = 2.5
LAST_SECONDS = 60
MIN_SECOND_COVERAGE = 55


def project_base() -> Path:
    return Path.home() / "Desktop" / "自动交易"


BASE = project_base()
DATA = BASE / "btc5m数据"
TRUE = DATA / "true_market"
DERIVED = DATA / "derived"
OUT_DIR = DERIVED / "backtest"
ARCHIVE = BASE / "旧文件"


def iter_jsonl(path: Path) -> Iterable[Dict[str, Any]]:
    if not path.exists():
        return
    with path.open("r", encoding="utf-8-sig", errors="ignore") as f:
        for line in f:
            line = line.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except Exception:
                continue
            if isinstance(row, dict):
                yield row


def find_files(name: str) -> List[Path]:
    paths: List[Path] = []
    if DATA.exists():
        paths.extend(DATA.rglob(name))
    if ARCHIVE.exists():
        paths.extend(ARCHIVE.rglob(name))
    seen = set()
    out = []
    for path in paths:
        key = str(path)
        if key in seen:
            continue
        seen.add(key)
        out.append(path)
    return out


def num(value: Any) -> Optional[float]:
    if value is None or value == "":
        return None
    try:
        v = float(value)
    except Exception:
        return None
    if math.isnan(v):
        return None
    return v


def parse_ts(value: Any) -> float:
    if not value:
        return 0.0
    try:
        return datetime.fromisoformat(str(value).replace("Z", "+00:00")).timestamp()
    except Exception:
        return 0.0


def row_ts(row: Dict[str, Any]) -> float:
    for key in ("server_ts", "received_at", "time"):
        ts = parse_ts(row.get(key))
        if ts:
            return ts
    for key in ("rtds_timestamp_ms", "timestamp_ms", "actual_entry_ts", "entry_time"):
        v = num(row.get(key))
        if v:
            return v / 1000 if v > 1_000_000_000_000 else v
    return 0.0


def fmt_time(ts: int) -> str:
    return datetime.fromtimestamp(ts, CN).strftime("%m-%d %H:%M:%S")


def load_integrity() -> List[Dict[str, Any]]:
    rows: List[Dict[str, Any]] = []
    for path in find_files("market_integrity.jsonl"):
        rows.extend(list(iter_jsonl(path) or []))
    rows.sort(key=lambda r: int(r.get("window_start_ts") or 0))
    dedup: Dict[str, Dict[str, Any]] = {}
    for row in rows:
        slug = str(row.get("slug") or "")
        if not slug:
            continue
        existing = dedup.get(slug)
        score = (
            1 if row.get("usable_for_backtest") else 0,
            int(row.get("price_ticks") or 0),
            int(row.get("orderbook_last120") or row.get("orderbook_ticks") or 0),
        )
        existing_score = (
            1 if (existing or {}).get("usable_for_backtest") else 0,
            int((existing or {}).get("price_ticks") or 0),
            int((existing or {}).get("orderbook_last120") or (existing or {}).get("orderbook_ticks") or 0),
        )
        if existing is None or score >= existing_score:
            dedup[slug] = row
    return sorted(dedup.values(), key=lambda r: int(r.get("window_start_ts") or 0))


def load_price_ticks(slugs: set[str]) -> Dict[str, Dict[int, float]]:
    out: Dict[str, Dict[int, float]] = defaultdict(dict)
    for path in find_files("price_ticks.jsonl"):
        for row in iter_jsonl(path) or []:
            slug = row.get("slug")
            if slug not in slugs:
                continue
            ts = row.get("rtds_timestamp_ms")
            ts_float = float(ts) / 1000 if ts else row_ts(row)
            value = num(row.get("value", row.get("price")))
            if ts_float and value and value > 1000:
                out[str(slug)][int(ts_float)] = float(value)
    return out


def parse_levels(levels: Any, side: str) -> List[Dict[str, float]]:
    parsed = []
    if not isinstance(levels, list):
        return parsed
    for item in levels:
        if not isinstance(item, dict):
            continue
        price = num(item.get("price"))
        size = num(item.get("size"))
        if price is None or size is None or price <= 0 or price >= 1 or size <= 0:
            continue
        parsed.append({"price": float(price), "size": float(size)})
    if side == "asks":
        parsed.sort(key=lambda x: x["price"])
    else:
        parsed.sort(key=lambda x: x["price"], reverse=True)
    return parsed


def side_from_obj(obj: Dict[str, Any]) -> Dict[str, Any]:
    return {
        "asks": parse_levels(obj.get("asks"), "asks"),
        "bids": parse_levels(obj.get("bids"), "bids"),
    }


def load_orderbook_snapshots(slugs: set[str]) -> Dict[str, List[Dict[str, Any]]]:
    books: Dict[str, Dict[str, Dict[str, Any]]] = defaultdict(dict)
    snapshots: Dict[str, List[Dict[str, Any]]] = defaultdict(list)
    for path in find_files("orderbook_ticks.jsonl"):
        for row in iter_jsonl(path) or []:
            slug = row.get("slug")
            if slug not in slugs:
                continue
            slug = str(slug)
            ts = row_ts(row)
            if not ts:
                continue
            if isinstance(row.get("up"), dict):
                books[slug]["up"] = side_from_obj(row["up"])
            if isinstance(row.get("down"), dict):
                books[slug]["down"] = side_from_obj(row["down"])
            side = str(row.get("side") or "").lower()
            if side in {"up", "down"}:
                books[slug][side] = {
                    "asks": parse_levels(row.get("asks"), "asks"),
                    "bids": parse_levels(row.get("bids"), "bids"),
                }
            if "up" in books[slug] and "down" in books[slug]:
                snapshots[slug].append({
                    "ts": float(ts),
                    "up": books[slug]["up"],
                    "down": books[slug]["down"],
                })
    for slug in list(snapshots):
        dedup = {}
        for snap in sorted(snapshots[slug], key=lambda r: r["ts"]):
            dedup[int(snap["ts"])] = snap
        snapshots[slug] = [dedup[k] for k in sorted(dedup)]
    return snapshots


def simulate_market_buy(asks: List[Dict[str, float]], amount_usd: float = AMOUNT_USD) -> Dict[str, Any]:
    if not asks:
        return {
            "avg_fill_price": 0.0,
            "shares": 0.0,
            "available_liquidity": 0.0,
            "fill_quality": "none",
            "cost": 0.0,
        }
    remaining = float(amount_usd)
    shares = 0.0
    cost = 0.0
    available_liquidity = sum(float(a["size"]) for a in asks)
    for ask in asks:
        price = float(ask["price"])
        size = float(ask["size"])
        max_shares = remaining / price
        buy_shares = min(max_shares, size)
        if buy_shares <= 0:
            continue
        line_cost = buy_shares * price
        shares += buy_shares
        cost += line_cost
        remaining -= line_cost
        if remaining <= 0.001:
            break
    if shares <= 0:
        avg = 0.0
        fill_quality = "none"
    else:
        avg = cost / shares
        fill_quality = "full" if remaining <= 0.001 else "partial" if cost > amount_usd * 0.5 else "none"
    return {
        "avg_fill_price": round(avg, 6),
        "shares": round(shares, 6),
        "available_liquidity": round(available_liquidity, 4),
        "fill_quality": fill_quality,
        "cost": round(cost, 6),
    }


def latest_snapshot_at(snapshots: List[Dict[str, Any]], ts: int) -> Optional[Dict[str, Any]]:
    if not snapshots:
        return None
    times = [s["ts"] for s in snapshots]
    idx = bisect_right(times, ts) - 1
    if idx < 0:
        return None
    return snapshots[idx]


@dataclass(frozen=True)
class Strategy:
    entry_second: int
    min_prob: float
    min_gap: float
    max_prob: float = 0.99
    min_seconds_left: int = 1
    max_orderbook_age: float = MAX_ORDERBOOK_AGE_SECONDS

    @property
    def name(self) -> str:
        return f"T{self.entry_second}_gap{int(self.min_gap)}_p{self.min_prob:.2f}"


def fee_for_trade(prob: float, shares: float) -> float:
    return shares * FEE_RATE * prob * (1 - prob)


def build_market_candidates(
    market: Dict[str, Any],
    price_ticks: Dict[int, float],
    snapshots: List[Dict[str, Any]],
) -> Dict[str, Any]:
    slug = market["slug"]
    end = int(market["window_end_ts"])
    open_price = float(market["open_price"])
    final_price = num(market.get("final_price"))
    final_gap = num(market.get("final_gap"))
    winner = "up" if final_gap is not None and final_gap >= 0 else "down"
    candidates: List[Dict[str, Any]] = []
    seconds_with_price = 0
    seconds_with_fresh_book = 0
    seconds_with_full_fill = 0

    for seconds_left in range(LAST_SECONDS, 0, -1):
        ts = end - seconds_left
        price = price_ticks.get(ts)
        if price is None:
            continue
        seconds_with_price += 1
        gap = price - open_price
        if abs(gap) < 1e-9:
            direction = "up"
        else:
            direction = "up" if gap > 0 else "down"
        snapshot = latest_snapshot_at(snapshots, ts)
        if not snapshot:
            continue
        age = float(ts) - float(snapshot["ts"])
        if age < -0.001 or age > MAX_ORDERBOOK_AGE_SECONDS:
            continue
        seconds_with_fresh_book += 1
        fill = simulate_market_buy(snapshot[direction]["asks"], AMOUNT_USD)
        if fill["fill_quality"] != "full":
            continue
        seconds_with_full_fill += 1
        prob = float(fill["avg_fill_price"])
        shares = float(fill["shares"])
        cost = float(fill["cost"] or AMOUNT_USD)
        fee = fee_for_trade(prob, shares)
        won = direction == winner
        pnl = shares * (1 - prob) - fee if won else -(cost + fee)
        candidates.append({
            "slug": slug,
            "market_time": market.get("market_time", ""),
            "entry_ts": ts,
            "entry_time": fmt_time(ts),
            "seconds_left": seconds_left,
            "direction": direction,
            "winner": winner,
            "open_price": round(open_price, 4),
            "entry_price": round(price, 4),
            "final_price": round(final_price, 4) if final_price is not None else None,
            "entry_gap": round(gap, 4),
            "final_gap": round(final_gap, 4) if final_gap is not None else None,
            "prob": prob,
            "shares": round(shares, 6),
            "cost": round(cost, 6),
            "fee": round(fee, 6),
            "pnl": round(pnl, 6),
            "won": won,
            "orderbook_age_seconds": round(age, 3),
            "available_liquidity": round(float(fill["available_liquidity"]), 4),
        })

    return {
        "market": market,
        "slug": slug,
        "candidate_seconds": candidates,
        "price_seconds": seconds_with_price,
        "fresh_orderbook_seconds": seconds_with_fresh_book,
        "full_fill_seconds": seconds_with_full_fill,
    }


def load_deep_usable_markets() -> Tuple[List[Dict[str, Any]], Dict[str, Any]]:
    all_rows = load_integrity()
    complete = [r for r in all_rows if r.get("usable_for_backtest")]
    slugs = {r["slug"] for r in complete}
    price_by_slug = load_price_ticks(slugs)
    books_by_slug = load_orderbook_snapshots(slugs)

    packaged: List[Dict[str, Any]] = []
    excluded = Counter()
    for market in complete:
        slug = market["slug"]
        bundle = build_market_candidates(market, price_by_slug.get(slug, {}), books_by_slug.get(slug, []))
        if bundle["price_seconds"] < MIN_SECOND_COVERAGE:
            excluded["price_coverage_below_min"] += 1
            continue
        if bundle["fresh_orderbook_seconds"] < MIN_SECOND_COVERAGE:
            excluded["orderbook_coverage_below_min"] += 1
            continue
        if bundle["full_fill_seconds"] < MIN_SECOND_COVERAGE:
            excluded["full_fill_coverage_below_min"] += 1
            continue
        packaged.append(bundle)
    packaged.sort(key=lambda x: int(x["market"]["window_start_ts"]))
    coverage = {
        "complete_markets": len(complete),
        "deep_usable_markets": len(packaged),
        "min_second_coverage_required": MIN_SECOND_COVERAGE,
        "excluded_reasons": dict(excluded),
        "coverage_medians": {
            "price_seconds": statistics.median([m["price_seconds"] for m in packaged]) if packaged else 0,
            "fresh_orderbook_seconds": statistics.median([m["fresh_orderbook_seconds"] for m in packaged]) if packaged else 0,
            "full_fill_seconds": statistics.median([m["full_fill_seconds"] for m in packaged]) if packaged else 0,
        },
        "time_range": {
            "first": packaged[0]["market"].get("market_time") if packaged else "",
            "last": packaged[-1]["market"].get("market_time") if packaged else "",
        },
    }
    return packaged, coverage


def evaluate_market(bundle: Dict[str, Any], strategy: Strategy) -> Dict[str, Any]:
    skip_reasons = Counter()
    for c in bundle["candidate_seconds"]:
        if c["seconds_left"] > strategy.entry_second or c["seconds_left"] < strategy.min_seconds_left:
            continue
        if abs(c["entry_gap"]) < strategy.min_gap:
            skip_reasons["gap_below_threshold"] += 1
            continue
        if c["prob"] < strategy.min_prob:
            skip_reasons["prob_below_min"] += 1
            continue
        if c["prob"] > strategy.max_prob:
            skip_reasons["prob_above_max"] += 1
            continue
        trade = dict(c)
        trade["status"] = "trade"
        trade["strategy_name"] = strategy.name
        return trade
    return {
        "slug": bundle["slug"],
        "market_time": bundle["market"].get("market_time", ""),
        "status": "skip",
        "skip_reasons": dict(skip_reasons) or {"no_eligible_second": 1},
    }


def max_drawdown(equity: List[float]) -> float:
    peak = 0.0
    worst = 0.0
    for value in equity:
        peak = max(peak, value)
        worst = min(worst, value - peak)
    return round(worst, 6)


def streaks(results: List[Dict[str, Any]]) -> Tuple[int, int]:
    best_win = best_loss = cur_win = cur_loss = 0
    for r in results:
        if r.get("status") != "trade":
            continue
        if r.get("won"):
            cur_win += 1
            cur_loss = 0
        else:
            cur_loss += 1
            cur_win = 0
        best_win = max(best_win, cur_win)
        best_loss = max(best_loss, cur_loss)
    return best_win, best_loss


def summarize(strategy: Strategy, bundles: List[Dict[str, Any]], results: List[Dict[str, Any]]) -> Dict[str, Any]:
    trades = [r for r in results if r.get("status") == "trade"]
    skips = [r for r in results if r.get("status") != "trade"]
    wins = sum(1 for r in trades if r.get("won"))
    losses = len(trades) - wins
    pnl_values = [float(r["pnl"]) for r in trades]
    equity = []
    running = 0.0
    for pnl in pnl_values:
        running += pnl
        equity.append(running)
    best_win, best_loss = streaks(results)
    skip_reasons = Counter()
    for r in skips:
        skip_reasons.update(r.get("skip_reasons") or {"no_signal": 1})
    entry_seconds = [int(r["seconds_left"]) for r in trades]
    entry_probs = [float(r["prob"]) for r in trades]
    entry_gaps = [abs(float(r["entry_gap"])) for r in trades]
    by_slug = {r["slug"]: r for r in results}
    time_buckets = defaultdict(lambda: {"markets": 0, "trades": 0, "wins": 0, "pnl": 0.0})
    for bundle in bundles:
        market = bundle["market"]
        dt = datetime.fromtimestamp(int(market["window_start_ts"]), CN)
        bucket = f"{dt.hour:02d}:00"
        item = time_buckets[bucket]
        item["markets"] += 1
        r = by_slug.get(bundle["slug"])
        if r and r.get("status") == "trade":
            item["trades"] += 1
            item["wins"] += 1 if r.get("won") else 0
            item["pnl"] += float(r.get("pnl") or 0)
    return {
        "strategy": {
            "name": strategy.name,
            "entry_second": strategy.entry_second,
            "min_prob": strategy.min_prob,
            "max_prob": strategy.max_prob,
            "min_gap": strategy.min_gap,
        },
        "sample_markets": len(bundles),
        "time_range": {
            "first": bundles[0]["market"].get("market_time") if bundles else "",
            "last": bundles[-1]["market"].get("market_time") if bundles else "",
        },
        "trades": len(trades),
        "skips": len(skips),
        "wins": wins,
        "losses": losses,
        "win_rate": round(wins / len(trades) * 100, 2) if trades else 0.0,
        "avg_pnl": round(statistics.mean(pnl_values), 6) if pnl_values else 0.0,
        "median_pnl": round(statistics.median(pnl_values), 6) if pnl_values else 0.0,
        "total_pnl": round(sum(pnl_values), 6),
        "max_drawdown": max_drawdown(equity),
        "longest_win_streak": best_win,
        "longest_loss_streak": best_loss,
        "avg_entry_second": round(statistics.mean(entry_seconds), 2) if entry_seconds else None,
        "median_entry_second": round(statistics.median(entry_seconds), 2) if entry_seconds else None,
        "avg_probability": round(statistics.mean(entry_probs), 6) if entry_probs else None,
        "avg_abs_gap": round(statistics.mean(entry_gaps), 4) if entry_gaps else None,
        "skip_reasons": dict(skip_reasons.most_common(8)),
        "time_buckets": {
            k: {
                **v,
                "pnl": round(v["pnl"], 6),
                "win_rate": round(v["wins"] / v["trades"] * 100, 2) if v["trades"] else 0.0,
            }
            for k, v in sorted(time_buckets.items())
        },
    }


def split_train_validation(bundles: List[Dict[str, Any]], ratio: float = 0.7) -> Tuple[List[Dict[str, Any]], List[Dict[str, Any]]]:
    cut = max(1, int(len(bundles) * ratio))
    if cut >= len(bundles):
        cut = max(0, len(bundles) - 1)
    return bundles[:cut], bundles[cut:]


def candidate_strategies() -> List[Strategy]:
    out = []
    for entry_second in range(1, LAST_SECONDS + 1):
        for min_prob_bp in range(95, 100):
            min_prob = min_prob_bp / 100
            for min_gap in range(20, 201, 5):
                out.append(Strategy(
                    entry_second=entry_second,
                    min_prob=min_prob,
                    min_gap=float(min_gap),
                ))
    return out


def evaluate_strategy(bundles: List[Dict[str, Any]], strategy: Strategy) -> Tuple[Dict[str, Any], List[Dict[str, Any]]]:
    results = [evaluate_market(bundle, strategy) for bundle in bundles]
    return summarize(strategy, bundles, results), results


def robustness_score(train_sum: Dict[str, Any], validation_sum: Dict[str, Any]) -> float:
    if train_sum["trades"] < 10 or validation_sum["trades"] < 10:
        return -9999.0
    validation_edge = validation_sum["total_pnl"]
    sample_bonus = min(validation_sum["trades"], 120) * 0.015
    drawdown_penalty = abs(validation_sum["max_drawdown"]) * 0.60 + abs(train_sum["max_drawdown"]) * 0.20
    loss_streak_penalty = validation_sum["longest_loss_streak"] * 0.75
    consistency_penalty = abs(validation_sum["win_rate"] - train_sum["win_rate"]) * 0.05
    return round(validation_edge + sample_bonus - drawdown_penalty - loss_streak_penalty - consistency_penalty, 6)


def simulate_staking(records: List[Dict[str, Any]], mode: str, initial: float = 10.0) -> Dict[str, Any]:
    bankroll = initial
    equity = [bankroll]
    active_records = []
    for r in records:
        if bankroll < 1.0:
            break
        if mode == "fixed_1":
            stake = 1.0
        elif mode == "fixed_fraction_10":
            stake = max(1.0, bankroll * 0.10)
        elif mode == "fixed_fraction_20":
            stake = max(1.0, bankroll * 0.20)
        else:
            raise ValueError(f"unknown mode: {mode}")
        stake = min(stake, bankroll)
        pnl_per_dollar = r["pnl"] / max(AMOUNT_USD, 1e-9)
        pnl = stake * pnl_per_dollar
        bankroll += pnl
        equity.append(bankroll)
        rr = dict(r)
        rr["stake"] = round(stake, 6)
        rr["scaled_pnl"] = round(pnl, 6)
        rr["bankroll_after"] = round(bankroll, 6)
        active_records.append(rr)
    wins = sum(1 for r in active_records if r["won"])
    return {
        "mode": mode,
        "initial": initial,
        "final_bankroll": round(bankroll, 6),
        "net_pnl": round(bankroll - initial, 6),
        "trades": len(active_records),
        "win_rate": round(wins / len(active_records) * 100, 2) if active_records else 0.0,
        "max_drawdown": max_drawdown([x - initial for x in equity[1:]]),
        "min_bankroll": round(min(equity), 6) if equity else initial,
    }


def simulate_pause_rule(
    records: List[Dict[str, Any]],
    mode: str,
    multiple: float,
    initial: float = 10.0,
    reset_after_lock: bool = True,
) -> Dict[str, Any]:
    bankroll = initial
    locked = 0.0
    active = True
    equity = []
    active_trades = 0
    skipped = 0
    pauses = 0
    wins = 0
    losses = 0
    resumes_after_loss = 0
    for r in records:
        if active:
            if bankroll < 1.0:
                break
            if mode == "fixed_1":
                stake = 1.0
            elif mode == "fixed_fraction_10":
                stake = max(1.0, bankroll * 0.10)
            elif mode == "fixed_fraction_20":
                stake = max(1.0, bankroll * 0.20)
            else:
                raise ValueError(f"unknown mode: {mode}")
            stake = min(stake, bankroll)
            pnl = stake * (r["pnl"] / AMOUNT_USD)
            bankroll += pnl
            active_trades += 1
            wins += 1 if r["won"] else 0
            losses += 0 if r["won"] else 1
            if bankroll >= initial * multiple:
                pauses += 1
                if reset_after_lock:
                    locked += bankroll - initial
                    bankroll = initial
                active = False
        else:
            skipped += 1
            if not r["won"]:
                active = True
                resumes_after_loss += 1
        equity.append(bankroll + locked)
    return {
        "mode": mode,
        "multiple": multiple,
        "reset_after_lock": reset_after_lock,
        "initial": initial,
        "final_total": round(bankroll + locked, 6),
        "active_bankroll": round(bankroll, 6),
        "locked_profit": round(locked, 6),
        "net_pnl": round(bankroll + locked - initial, 6),
        "active_trades": active_trades,
        "skipped_signals": skipped,
        "pauses": pauses,
        "resumes_after_loss": resumes_after_loss,
        "win_rate_active": round(wins / active_trades * 100, 2) if active_trades else 0.0,
        "max_drawdown_total": max_drawdown([x - initial for x in equity]),
    }


def main() -> int:
    OUT_DIR.mkdir(parents=True, exist_ok=True)
    bundles, data_scope = load_deep_usable_markets()
    train, validation = split_train_validation(bundles, 0.7)
    candidates = candidate_strategies()

    train_rows: List[Dict[str, Any]] = []
    validation_rows: List[Dict[str, Any]] = []
    results_cache: Dict[str, List[Dict[str, Any]]] = {}

    for strategy in candidates:
        train_summary, _ = evaluate_strategy(train, strategy)
        validation_summary, _ = evaluate_strategy(validation, strategy)
        if train_summary["trades"] <= 0:
            continue
        row = {
            "strategy": train_summary["strategy"],
            "train": train_summary,
            "validation": validation_summary,
            "robustness_score": robustness_score(train_summary, validation_summary),
        }
        train_rows.append(row)
        validation_rows.append(row)

    robust_rows = sorted(
        train_rows,
        key=lambda x: (
            x["robustness_score"],
            x["validation"]["total_pnl"],
            x["validation"]["win_rate"],
            x["validation"]["trades"],
        ),
        reverse=True,
    )
    top_validation = sorted(
        train_rows,
        key=lambda x: (
            x["validation"]["total_pnl"],
            x["validation"]["win_rate"],
            x["validation"]["trades"],
        ),
        reverse=True,
    )

    selected_row = robust_rows[0] if robust_rows else None
    selected_strategy = None
    selected_all_summary = None
    selected_all_results: List[Dict[str, Any]] = []
    staking_modes = []
    pause_rules = []
    if selected_row:
        selected_strategy = Strategy(
            entry_second=int(selected_row["strategy"]["entry_second"]),
            min_prob=float(selected_row["strategy"]["min_prob"]),
            min_gap=float(selected_row["strategy"]["min_gap"]),
            max_prob=float(selected_row["strategy"]["max_prob"]),
        )
        selected_all_summary, selected_all_results = evaluate_strategy(bundles, selected_strategy)
        selected_trades = [r for r in selected_all_results if r.get("status") == "trade"]
        staking_modes = [simulate_staking(selected_trades, m) for m in ("fixed_1", "fixed_fraction_10", "fixed_fraction_20")]
        for multiple in (1.2, 1.5, 2.0, 3.0, 5.0):
            for mode in ("fixed_1", "fixed_fraction_10", "fixed_fraction_20"):
                pause_rules.append(simulate_pause_rule(selected_trades, mode, multiple, reset_after_lock=True))
                pause_rules.append(simulate_pause_rule(selected_trades, mode, multiple, reset_after_lock=False))

    report = {
        "generated_at": datetime.now(CN).isoformat(),
        "data_scope": data_scope,
        "train_validation_split": {
            "train_markets": len(train),
            "validation_markets": len(validation),
            "train_time_range": {
                "first": train[0]["market"].get("market_time") if train else "",
                "last": train[-1]["market"].get("market_time") if train else "",
            },
            "validation_time_range": {
                "first": validation[0]["market"].get("market_time") if validation else "",
                "last": validation[-1]["market"].get("market_time") if validation else "",
            },
        },
        "scan_space": {
            "entry_second_range": [1, LAST_SECONDS],
            "probability_range": [0.95, 0.99],
            "gap_range": [20, 200],
            "gap_step": 5,
            "strategy_count": len(candidates),
        },
        "top_robust_strategies": robust_rows[:25],
        "top_validation_strategies": top_validation[:25],
        "selected_strategy_all_markets": selected_all_summary,
        "selected_strategy_staking_modes": staking_modes,
        "selected_strategy_pause_rules_top": sorted(
            pause_rules,
            key=lambda r: (r["net_pnl"], -r["max_drawdown_total"], r["active_trades"]),
            reverse=True,
        )[:20],
        "selected_strategy_trade_samples": [r for r in selected_all_results if r.get("status") == "trade"][:40],
        "interpretation_flags": [
            "strict deep backtest uses current complete markets only",
            "signals are derived from official price_ticks plus Polymarket orderbook snapshots",
            "pause-after-profit rules are tested on the same chronological sequence and still need forward validation",
        ],
    }
    out_json = OUT_DIR / "btc5m_backtest_deep.json"
    out_json.write_text(json.dumps(report, ensure_ascii=False, indent=2), encoding="utf-8")
    print(json.dumps({
        "output": str(out_json),
        "data_scope": data_scope,
        "split": report["train_validation_split"],
        "scan_space": report["scan_space"],
        "selected_strategy_all_markets": selected_all_summary,
        "selected_strategy_staking_modes": staking_modes,
        "selected_strategy_pause_rules_top": report["selected_strategy_pause_rules_top"][:8],
    }, ensure_ascii=False, indent=2))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
