const S={tab:"trade",tradePage:1,userPage:1,safety:{},status:{},config:{},summary:{},charts:{},modalType:null};
const $=s=>document.querySelector(s);
const $$=s=>document.querySelectorAll(s);
const esc=s=>{const d=document.createElement("div");d.textContent=s||"";return d.innerHTML};
const fm=(n,d)=>(Number(n)||0).toFixed(d||2);
const fM=n=>n<0?"-$"+fm(Math.abs(n)):"$"+fm(n||0);
const fP=n=>fm((n||0)*100,1)+"%";
function api(p,o){o=o||{};const h={"Content-Type":"application/json"};if(o.headers)Object.assign(h,o.headers);return fetch(p,Object.assign({},o,{headers:h})).then(r=>{if(!r.ok)return r.json().catch(()=>({error:r.status})).then(e=>{throw new Error(e.error||r.status)});return r.json()})}
function toast(m){const el=$("#toastMsg");if(!el)return;el.textContent=m;el.style.opacity="1";clearTimeout(el._t);el._t=setTimeout(()=>{el.style.opacity="0"},3000)}
function initMatrixRain(){const c=document.createElement("canvas");c.id="matrixCanvas";c.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;z-index:0;pointer-events:none;opacity:0.06";document.body.prepend(c);const ctx=c.getContext("2d");c.width=window.innerWidth;c.height=window.innerHeight;const chars="ABC123XYZ";const fs=14;const cols=Math.floor(c.width/fs);const dr=Array(cols).fill(1);function d(){ctx.fillStyle="rgba(13,2,33,0.05)";ctx.fillRect(0,0,c.width,c.height);ctx.fillStyle="#05d9e8";ctx.font=fs+"px monospace";for(let i=0;i<dr.length;i++){const t=chars[Math.floor(Math.random()*chars.length)];ctx.fillText(t,i*fs,dr[i]*fs);if(dr[i]*fs>c.height&&Math.random()>0.975)dr[i]=0;dr[i]++}}setInterval(d,50)}
function initParticles(){const c=document.createElement("canvas");c.style.cssText="position:fixed;top:0;left:0;width:100%;height:100%;z-index:0;pointer-events:none;opacity:0.15";document.body.prepend(c);const ctx=c.getContext("2d");c.width=window.innerWidth;c.height=window.innerHeight;const ps=Array.from({length:60},()=>({x:Math.random()*c.width,y:Math.random()*c.height,vx:(Math.random()-0.5)*0.5,vy:(Math.random()-0.5)*0.5,r:Math.random()*2+1}));function d(){ctx.clearRect(0,0,c.width,c.height);ps.forEach(p=>{p.x+=p.vx;p.y+=p.vy;if(p.x<0||p.x>c.width)p.vx*=-1;if(p.y<0||p.y>c.height)p.vy*=-1;ctx.beginPath();ctx.arc(p.x,p.y,p.r,0,Math.PI*2);ctx.fillStyle="#ff2a6d";ctx.fill()})}setInterval(d,50)}
function updateClock(){const n=new Date();$("#currentTime").textContent=n.toLocaleTimeString("zh-CN",{hour12:false})}
setInterval(updateClock,1000);updateClock();
function loadAll(){Promise.all([api("/api/safety").catch(()=>({})),api("/api/status").catch(()=>({})),api("/api/config").catch(()=>({strategies:{}})),api("/api/summary").catch(()=>({daily_summary:[]}))]).then(([safety,status,config,summary])=>{S.safety=safety;S.status=status;S.config=config;S.summary=summary;renderAll()})}
function renderAll(){updateTicker();updateHeader();updatePortfolio();updateStatusCards();updateSignalMetrics();updateStrategies();updateModeUI();updateCountdown();checkTabRefresh()}
function updateTicker(){const st=S.status||{},t=st.ticker||{},ga=Number(t.gap||0);const eg=$("#tickerGap"),eb=$("#tickerBtc"),ep=$("#tickerPtb"),es=$("#tickerSource");if(eg){eg.textContent="GAP "+(ga>0?"+":"")+fm(ga);eg.style.color=ga>=0?"var(--neon-green)":"var(--neon-pink)"}if(eb)eb.textContent="$"+fm(t.btc_price||0);if(ep)ep.textContent="$"+fm(t.ptb||0);if(es)es.textContent=(t.source||"--")+" "+(t.data_age_seconds!=null?fm(t.data_age_seconds,1)+"s":"");const fl=$("#footerLatency"),fd=$("#footerDataSource");if(fl)fl.textContent=t.data_age_seconds!=null?fm(t.data_age_seconds,1)+"s":"--";if(fd)fd.textContent=t.source||"--"}
function updateHeader(){const ts=(S.status||{}).trader_state||{},sf=S.safety||{},b=$("#headerBalance");if(b)b.textContent=fM(ts.bankroll||0);const mb=$("#modeBadge");if(mb){mb.textContent=sf.mode==="live"?"LIVE":"SIM";mb.style.color=sf.mode==="live"?"var(--neon-pink)":"var(--neon-blue)"}}
function updatePortfolio(){const ts=(S.status||{}).trader_state||{},sm=S.summary||{};let b=ts.bankroll||0,t=ts.trade_count||0,w=ts.win_count||0,l=ts.loss_count||0;if((sm.total||0)>t){t=sm.total||0;w=sm.won||0;l=sm.lost||0}const wr=t>0?fm(w/t*100,1):"--",pn=sm.total_pnl||0;$("#statBankroll")&&($("#statBankroll").textContent=fM(b));$("#statTrades")&&($("#statTrades").textContent=t);$("#statWinRate")&&($("#statWinRate").textContent=wr+"%");const sp=$("#statPnl");if(sp){sp.textContent=fM(pn);sp.style.color=pn>=0?"var(--neon-green)":"var(--neon-pink)"}}
function updateStatusCards(){const ts=(S.status||{}).trader_state||{},sm=S.summary||{};$("#scBankroll")&&($("#scBankroll").textContent=fM(ts.bankroll||0));$("#scTrades")&&($("#scTrades").textContent=sm.total||ts.trade_count||0);$("#scWins")&&($("#scWins").textContent=sm.won||ts.win_count||0);$("#scLosses")&&($("#scLosses").textContent=sm.lost||ts.loss_count||0)}
function updateSignalMetrics(){const st=S.status||{},t=st.ticker||{},m=st.current_market||{},ga=Number(t.gap||0);$("#sigBtc")&&($("#sigBtc").textContent="$"+fm(t.btc_price||0));$("#sigPtb")&&($("#sigPtb").textContent="$"+fm(t.ptb||0));const sg=$("#sigGap");if(sg){sg.textContent=(ga>0?"+":"")+fm(ga);sg.style.color=ga>=0?"var(--neon-green)":"var(--neon-pink)"}const sud=$("#sigUpDown");if(sud)sud.innerHTML='<span style="color:var(--neon-green)">'+fm(t.up_price||0,3)+'</span><span style="color:var(--neon-pink)"> / '+fm(t.down_price||0,3)+"</span>";const wp=$("#windowProgress"),wb=$("#windowBar");if(m.seconds_left!=null&&wp)wp.textContent=m.seconds_left+"s";if(m.seconds_left!=null&&wb)wb.style.width=((300-m.seconds_left)/300*100)+"%"}
function updateCountdown(){const m=(S.status||{}).current_market||{},sl=m.seconds_left;if(sl!=null){const mn=Math.floor(sl/60),sc=sl%60;$("#cd-hours")&&($("#cd-hours").textContent="00");$("#cd-minutes")&&($("#cd-minutes").textContent=mn.toString().padStart(2,"0"));$("#cd-seconds")&&($("#cd-seconds").textContent=sc.toString().padStart(2,"0"))}else{["cd-hours","cd-minutes","cd-seconds"].forEach(id=>{const e=$(id);if(e)e.textContent="--"})}}
function updateStrategies(){const cfg=S.config||{},sts=cfg.strategies||{},ai=cfg.active_strategy||"1",g=$("#strategyGrid");if(!g)return;$("#activeStratLabel")&&($("#activeStratLabel").textContent=sts[ai]?sts[ai].name:"");let h="";for(const k in sts){const s=sts[k],p=s.params||{},ia=k===ai;h+='<div class="strat-slot bg-gray-900 bg-opacity-50 p-3 rounded border '+(ia?"active":"border-gray-800")+'" onclick="selectStrategy('+k+')"><div style="color:'+(ia?"var(--neon-pink)":"white")+'" class="text-sm font-bold">'+esc(s.name)+'</div><div class="text-xs text-gray-500 mt-1">'+(s.win_rate||"--")+'%</div><div>入场'+(p.entry_second||25)+"s $"+(p.gap_threshold||10)+" "+fP(p.min_buy_price||0.6)+"</div></div>"}g.innerHTML=h;const ed=$("#strategyEditor"),as=sts[ai];if(as&&as.params){const p=as.params;ed.style.display="block";ed.innerHTML="";ed.innerHTML='<div class="flex items-center justify-between mb-2"><span class="text-sm neon-text-pink">'+esc(as.name)+" ID:"+ai+'</span></div><div class="grid grid-cols-3 md:grid-cols-6 gap-2">'+
'<div><label class="text-xs text-gray-500">入场(s)</label><br><input class="param-input" id="spEntry" value="'+(p.entry_second||25)+'"></div>'+
'<div><label class="text-xs text-gray-500">Gap($)</label><br><input class="param-input" id="spGap" value="'+(p.gap_threshold||10)+'"></div>'+
'<div><label class="text-xs text-gray-500">概率</label><br><input class="param-input" id="spMinPrice" value="'+(p.min_buy_price||0.6)+'" step="0.01"></div>'+
'<div><label class="text-xs text-gray-500">仓位</label><br><select class="param-input" id="spFraction"><option value="1.0" selected>100%</option><option value="0.5">50%</option><option value="0.25">25%</option></select></div>'+
'<div><label class="text-xs text-gray-500">冷却(s)</label><br><input class="param-input" id="spCooldown" value="'+(p.cooldown_seconds||0)+'"></div>'+
'<div><label class="text-xs text-gray-500">最高价</label><br><input class="param-input" id="spMaxPrice" value="'+(p.max_buy_price||0.99)+'" step="0.01"></div></div>'+
'<button class="btn-cyber sm mt-2" onclick="saveStrategy()">Save</button>'}else{ed.style.display="none"}}
function selectStrategy(id){if(id===(S.config||{}).active_strategy)return;api("/api/strategies/switch",{method:"POST",body:JSON.stringify({strategy_id:id})}).then(()=>{S.config.active_strategy=id;toast("Switched to strategy "+id);updateStrategies()}).catch(e=>toast(e.message))}
function saveStrategy(){const ai=(S.config||{}).active_strategy||"1",p={entry_second:parseInt($("#spEntry")?.value)||25,gap_threshold:parseInt($("#spGap")?.value)||10,min_buy_price:parseFloat($("#spMinPrice")?.value)||0.6,bet_fraction:parseFloat($("#spFraction")?.value)||1.0,cooldown_seconds:parseInt($("#spCooldown")?.value)||0,max_buy_price:parseFloat($("#spMaxPrice")?.value)||0.99};api("/api/strategies/update",{method:"POST",body:JSON.stringify({strategy_id:ai,params:p})}).then(()=>{toast("Saved");loadAll()}).catch(e=>toast(e.message))}
function setMode(md){const cur=(S.safety||{}).mode||"sim";if(cur===md)return;api("/api/config",{method:"POST",body:JSON.stringify({mode:md})}).then(()=>{toast(md==="live"?"Live":"Sim");loadAll()}).catch(e=>toast(e.message))}
function updateModeUI(){const sf=S.safety||{},md=sf.mode||"sim",ps=md==="live"?sf.paused!==false:sf.sim_paused!==false,ar=sf.armed||false;$("#modeSimBtn")&&($("#modeSimBtn").style.borderColor=md==="sim"?"var(--neon-green)":"");$("#modeLiveBtn")&&($("#modeLiveBtn").style.borderColor=md==="live"?"var(--neon-pink)":"");const tb=$("#toggleBtn");if(tb){tb.innerHTML=ps?"Play":"Pause";tb.className="btn-cyber"+(ps?" green":"")}const ab=$("#armBtn");if(ab){ab.style.display=md==="live"?"inline-block":"none";ab.innerHTML=ar?"Disarm":"Arm Live";ab.className="btn-cyber"+(ar?" green sm":" danger sm")}}
function togglePause(){const sf=S.safety||{},md=sf.mode||"sim",ps=md==="live"?sf.paused!==false:sf.sim_paused!==false;api("/api/toggle",{method:"POST",body:JSON.stringify({action:ps?"start":"pause"})}).then(()=>{toast(ps?"Started":"Paused");loadAll()}).catch(e=>toast(e.message))}
function toggleArm(){const sf=S.safety||{};if(sf.armed){api("/api/live/arm",{method:"POST",body:JSON.stringify({armed:false})}).then(()=>{toast("Disarmed");loadAll()}).catch(e=>toast(e.message))}else{const c=prompt("Confirm code (BTC5M-LIVE):");if(!c)return;api("/api/live/arm",{method:"POST",body:JSON.stringify({armed:true,confirm:c,max_live_amount:1})}).then(()=>{toast("LIVE ARMED!");loadAll()}).catch(e=>toast(e.message))}}
function switchTab(t){S.tab=t;$$(".cyber-tab").forEach(el=>el.classList.toggle("active",el.dataset.tab===t));$$(".tab-content").forEach(el=>el.classList.toggle("active",el.id==="tab-"+t));if(t==="daily")setTimeout(renderDailyCharts,200);if(t==="user")setTimeout(loadUserTrades,100)}
function checkTabRefresh(){if(S.tab==="daily")setTimeout(renderDailyCharts,100);if(S.tab==="user")setTimeout(loadUserTrades,50)}
function renderDailyCharts(){const sm=S.summary||{},ds=sm.daily_summary||[];if(!ds.length){$("#pnlChart")&&($("#pnlChart").innerHTML='<p style="text-align:center;padding:60px 0;color:gray">No data</p>');$("#volChart")&&($("#volChart").innerHTML='<p style="text-align:center;padding:60px 0;color:gray">No data</p>');updateDailyDetail();return}const lb=ds.map(x=>x.date),pn=ds.map(x=>Number(x.pnl||0)),vl=ds.map(x=>x.trades||0),cl=pn.map(v=>v>=0?"#00ff9d":"#ff2a6d");try{if(S.charts.pnl)S.charts.pnl.dispose();S.charts.pnl=echarts.init($("#pnlChart"));S.charts.pnl.setOption({tooltip:{trigger:"axis",formatter:p=>p[0].axisValue+" "+fM(p[0].value)},grid:{left:55,right:15,top:20,bottom:30},xAxis:{type:"category",data:lb,axisLabel:{color:"rgba(255,255,255,0.5)",fontSize:10}},yAxis:{type:"value",axisLabel:{color:"rgba(255,255,255,0.5)",formatter:v=>"$"+v},splitLine:{lineStyle:{color:"rgba(255,255,255,0.05)"}}},series:[{type:"bar",data:pn.map((v,i)=>({value:v,itemStyle:{color:cl[i]}})),barWidth:"50%"}]})}catch(e){}$("#volChart")&&echarts&&(S.charts.vol?S.charts.vol.dispose():0,S.charts.vol=echarts.init($("#volChart")),S.charts.vol.setOption({tooltip:{trigger:"axis"},grid:{left:55,right:15,top:20,bottom:30},xAxis:{type:"category",data:lb,axisLabel:{color:"rgba(255,255,255,0.5)",fontSize:10}},yAxis:{type:"value",axisLabel:{color:"rgba(255,255,255,0.5)"},splitLine:{lineStyle:{color:"rgba(255,255,255,0.05)"}}},series:[{type:"bar",data:vl,itemStyle:{color:"#05d9e8"},barWidth:"50%"}]));updateDailyDetail()}
function updateDailyDetail(){api("/api/daily-detail").then(rows=>{const el=$("#dailyDetail");if(!el)return;if(!rows||!rows.length){el.innerHTML='<p style="text-align:center;padding:20px;color:gray">No data</p>';return}let h='<div class="tbl-wrap"><table class="tbl"><tr><th>Date</th><th>Trades</th><th>PNL</th><th>Wins</th><th>Loss</th><th>Skip</th><th>Volume</th></tr>';rows.forEach(r=>{h+="<tr><td>"+esc(r.date)+"</td><td>"+(r.trades||0)+'</td><td style="color:'+(Number(r.pnl||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+fM(r.pnl||0)+'</td><td style="color:var(--neon-green)">'+(r.wins||0)+'</td><td style="color:var(--neon-pink)">'+(r.losses||0)+"</td><td>"+(r.skipped||0)+"</td><td>"+fM(r.volume||0)+"</td></tr>"});h+="</table></div>";el.innerHTML=h}).catch(()=>{})}
function loadUserTrades(){const st=S.status||{},m=st.current_market||{},t=st.ticker||{},ts=st.trader_state||{};$("#userMarketInfo")&&($("#userMarketInfo").innerHTML='<div class="border-b border-gray-800 py-1 flex justify-between"><span>Market</span><span>'+(m.slug||"btc-5m")+'</span></div><div class="border-b border-gray-800 py-1 flex justify-between"><span>Remaining</span><span>'+(m.seconds_left!=null?m.seconds_left+"s":"--")+'</span></div><div class="border-b border-gray-800 py-1 flex justify-between"><span>BTC</span><span>$'+fm(t.btc_price||0)+'</span></div><div class="border-b border-gray-800 py-1 flex justify-between"><span>PTB</span><span>$'+fm(t.ptb||0)+'</span></div><div class="border-b border-gray-800 py-1 flex justify-between"><span>Gap</span><span style="color:'+(Number(t.gap||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+(Number(t.gap||0)>0?"+":"")+fm(t.gap||0)+'</span></div><div class="border-b border-gray-800 py-1 flex justify-between"><span>Up/Dn</span><span>'+fm(t.up_price||0,3)+"/"+fm(t.down_price||0,3)+'</span></div><div class="py-1 flex justify-between"><span>Source</span><span>'+(t.source||"--")+'</span></div>');const us=$("#userStats");if(us){const sm=S.summary||{},tr=(S.status||{}).trader_state||{},tt=sm.total||tr.trade_count||0,tw=sm.won||tr.win_count||0,tl=sm.lost||tr.loss_count||0,tpn=sm.total_pnl||0;us.innerHTML='<div class="bg-gray-900 bg-opacity-50 p-3 rounded border border-gray-800 text-center"><div class="text-xl neon-text-blue">'+tt+'</div><div class="text-xs text-gray-500">Trades</div></div><div class="bg-gray-900 bg-opacity-50 p-3 rounded border border-gray-800 text-center"><div style="color:var(--neon-green)" class="text-xl">'+tw+'</div><div class="text-xs text-gray-500">Wins</div></div><div class="bg-gray-900 bg-opacity-50 p-3 rounded border border-gray-800 text-center"><div style="color:var(--neon-pink)" class="text-xl">'+tl+'</div><div class="text-xs text-gray-500">Loss</div></div><div class="bg-gray-900 bg-opacity-50 p-3 rounded border border-gray-800 text-center"><div style="color:'+(tpn>=0?"var(--neon-green)":"var(--neon-pink)")+'" class="text-xl">'+fM(tpn)+'</div><div class="text-xs text-gray-500">PNL</div></div>'}loadUserTradePage(S.userPage||1)}
function loadUserTradePage(pg){S.userPage=pg;api("/api/trades?p="+pg+"&ps=20").then(r=>{const el=$("#userTradeTable");if(!el)return;if(!r||!r.trades||!r.trades.length){el.innerHTML='<p style="text-align:center;padding:20px;color:gray">No trades</p>';return}const fS=s=>{if(s==="won"||s==="matched")return"OK";if(s==="skipped")return"SKIP";return"FAIL"};const fD=d=>d==="up"?"Up":"Down";let h='<div class="tbl-wrap"><table class="tbl"><tr><th>St</th><th>Time</th><th>Dir</th><th>Open</th><th>Entry</th><th>Settle</th><th>EGap</th><th>SGap</th><th>Prob</th><th>Amt</th><th>In</th><th>PNL</th><th>Ret</th><th>Why</th></tr>';r.trades.forEach(t=>{h+="<tr>"+(t.status==="won"?"<td style=color:var(--neon-green)>OK</td>":t.status==="skipped"?"<td style=color:var(--neon-pink)>SKIP</td>":"<td>FAIL</td>")+'<td style="font-size:10px">'+(t.time?t.time.slice(5,19):"")+"</td><td>"+fD(t.direction)+"</td><td>$"+fm(t.btc_open,0)+"</td><td>$"+fm(t.btc_entry,0)+"</td><td>$"+fm(t.btc_final,0)+'</td><td style="color:'+(Number(t.entry_gap||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+(Number(t.entry_gap||0)>0?"+":"")+fm(t.entry_gap)+'</td><td style="color:'+(Number(t.settle_gap||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+(Number(t.settle_gap||0)>0?"+":"")+fm(t.settle_gap)+"</td><td>"+fP(t.buy_prob)+"</td><td>$"+fm(t.buy_amount)+'</td><td style="font-size:10px">'+(t.time?t.time.slice(11,19):"")+'</td><td style="color:'+(Number(t.net_profit||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+fM(t.net_profit)+'</td><td style="color:'+(Number(t.return_pct||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+(Number(t.return_pct||0)>0?"+":"")+fm(t.return_pct,1)+'%</td><td style="font-size:10px;max-width:100px">'+esc(t.skip_reason||(t.status==="won"?"OK":t.status==="matched_lost"?"Loss":"--"))+"</td></tr>"});h+="</table></div>";if(r.pages>1){h+='<div class="pages">';for(let i=1;i<=r.pages;i++)h+='<button class="btn-cyber sm '+(i===pg?"cur":"")+'" onclick="loadUserTradePage('+i+')">'+i+"</button>";h+='<span style="font-size:10px;color:gray"> '+r.total+" items</span></div>"}el.innerHTML=h}).catch(()=>{})}
function showHistory(){S.modalType="history";const ov=$("#modalOverlay");if(!ov)return;ov.style.display="flex";S.userPage=1;$("#modalContent")&&($("#modalContent").innerHTML='<div style="display:flex;justify-content:space-between;margin-bottom:12px"><h3 style="color:var(--neon-blue)">Trade History</h3></div><div id="modalTradeTable"><p style="text-align:center;padding:20px;color:gray">Loading...</p></div>');loadModalTrade(1)}
function loadModalTrade(pg){S.userPage=pg;api("/api/trades?p="+pg+"&ps=20").then(r=>{const el=$("#modalTradeTable");if(!el)return;if(!r||!r.trades||!r.trades.length){el.innerHTML='<p style="text-align:center;padding:20px;color:gray">No trades</p>';return}let h='<div class="tbl-wrap"><table class="tbl"><tr><th>St</th><th>Time</th><th>Dir</th><th>Open</th><th>Entry</th><th>Settle</th><th>EGap</th><th>SGap</th><th>Prob</th><th>Amt</th><th>In</th><th>PNL</th><th>Ret</th><th>Why</th></tr>';r.trades.forEach(t=>{h+="<tr>"+(t.status==="won"?"<td style=color:var(--neon-green)>OK</td>":t.status==="skipped"?"<td style=color:var(--neon-pink)>SKIP</td>":"<td>FAIL</td>")+'<td style="font-size:10px">'+(t.time?t.time.slice(5,19):"")+"</td><td>"+(t.direction==="up"?"Up":"Down")+"</td><td>$"+fm(t.btc_open,0)+"</td><td>$"+fm(t.btc_entry,0)+"</td><td>$"+fm(t.btc_final,0)+'</td><td style="color:'+(Number(t.entry_gap||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+(Number(t.entry_gap||0)>0?"+":"")+fm(t.entry_gap)+'</td><td style="color:'+(Number(t.settle_gap||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+(Number(t.settle_gap||0)>0?"+":"")+fm(t.settle_gap)+"</td><td>"+fP(t.buy_prob)+"</td><td>$"+fm(t.buy_amount)+'</td><td style="font-size:10px">'+(t.time?t.time.slice(11,19):"")+'</td><td style="color:'+(Number(t.net_profit||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+fM(t.net_profit)+'</td><td style="color:'+(Number(t.return_pct||0)>=0?"var(--neon-green)":"var(--neon-pink)")+'">'+(Number(t.return_pct||0)>0?"+":"")+fm(t.return_pct,1)+'%</td><td style="font-size:10px;max-width:100px">'+esc(t.skip_reason||"--")+"</td></tr>"});h+="</table></div>";if(r.pages>1){h+='<div class="pages">';for(let i=1;i<=r.pages;i++)h+='<button class="btn-cyber sm '+(i===pg?"cur":"")+'" onclick="loadModalTrade('+i+')">'+i+"</button>";h+='<span style="font-size:10px;color:gray"> '+r.total+"</span></div>"}el.innerHTML=h}).catch(()=>{})}
function closeModal(){const ov=$("#modalOverlay");if(ov)ov.style.display="none";S.modalType=null}
document.addEventListener("click",function(e){const ov=$("#modalOverlay");if(ov&&e.target===ov)closeModal()});
document.addEventListener("DOMContentLoaded",function(){initMatrixRain();initParticles();$$(".cyber-tab").forEach(el=>{el.dataset.tab=el.textContent.includes("交易")?"trade":el.textContent.includes("每日")?"daily":"user"});loadAll();setInterval(loadAll,5000);window.addEventListener("resize",()=>{for(const k in S.charts){const c=S.charts[k];if(c&&c.resize)c.resize()}})});
